name: 每月存档

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create archive directory
        run: |
          if [ ! -d "archive" ]; then
            mkdir archive
          fi

      - name: Set timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m')"

      - name: Create archive
        run: tar -czvf "archive/monthly_archive_${{ steps.timestamp.outputs.timestamp }}.tar.gz" hotlist/*.csv

      - name: Delete original data
        run: rm -rf hotlist/*.csv

      - name: Git add and commit
        run: |
          git config --global user.email "ouweijie123@outlook.com"
          git config --global user.name "archiver actioner"
          git add .
          git commit -m "monthly_archive_${{ steps.timestamp.outputs.timestamp }}"

      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          branch: master